### ISSUE TITLE
🐛 [firebase_ui_auth] User unable to add photo to ProfileScreen page if registering via email and password

### ISSUE THREAD

**Issue by hdbookie** [firebase/FirebaseUI-Flutter#50]
## Bug report

**Describe the bug**
I was exploring using this package for a profile/account page and I'm satisified with it for google sign in, but if a user registers via email and password they don't have an option to upload their own photo.

### Steps to reproduce

1. Register a user with the package with email and password
2. Navigate to the ProfileScreen page from the package
3. You will be unable to add a photo

### Expected behavior

I expected a photo add button on the blank photo.

**Comment by Tobicic** [comment]
One year later ... any good news about changing profile photo url?

**Comment by lesnitsky** [comment]
`ProfileScreen` now has an `avatar` property that could be passed down.
`firebase_ui_storage` has a `StorageImage` that could be used to show custom user avatars.
I don't think there's much left to do from the `firebase_ui_auth` perspective, since `firebase_auth` doesn't allow updating `photoURL` of the `User`
